__author__ = 'Yaroslav'

CONFIG_ERLANG_RUNTIME = "erlang_runtime"
CONFIG_PLT_FILE_PATH = "plt_file_path"
CONFIG_HOME_PATH = "home_path"
CONFIG_EXCLUDED_DIRS = "excluded_dirs"
CONFIG_EXCLUDED_PATHS = "excluded_paths"
CONFIG_COMPILER_OPTIONS = "compiler_options"
CONFIG_FLY_COMPILE = "fly_compile"
CONFIG_APPS_DIR = "apps_dir"
CONFIG_DEPS_DIR = "deps_dir"
CONFIG_WORK_DIR = "work_dir"

CONFIG_CONSOLES = "consoles"
CONFIG_PROJECT_TYPE = "erlang_project_type"
CONFIG_CONSOLE_SNAME = "sname"
CONFIG_CONSOLE_COOKIE = "cookie"
CONFIG_CONSOLE_PARAMS = "params"
CONFIG_CONSOLE_COMMAND = "command"

TYPE_MODULE, TYPE_HRL, TYPE_UNKNOWN = range(3)

TASK_COMPILE, TASK_COMPILE_FLY, TASK_GEN_FILE_CACHE, TASK_GEN_ERLANG_CACHE, \
TASK_COMPILE_APP, TASK_CACHE_APP = range(6)

SINGLE_APP_PROJECT = "Single app"
MULTIPLE_APP_PROJECT = "Multiple apps"