__author__ = 'Yaroslav'

CONFIG_ERLANG_RUNTIME = "erlang_runtime"
CONFIG_PLT_FILE_PATH = "plt_file_path"
CONFIG_HOME_PATH = "home_path"
CONFIG_EXCLUDED_DIRS = "excluded_dirs"
CONFIG_COMPILER_OPTIONS = "compiler_options"
CONFIG_FLY_COMPILE = "fly_compile"
CONFIG_APPS_DIR = "apps_dir"

CONFIG_CONSOLES = "consoles"
CONFIG_CONSOLE_SNAME = "sname"
CONFIG_CONSOLE_COOKIE = "cookie"
CONFIG_CONSOLE_PARAMS = "params"
CONFIG_CONSOLE_COMMAND = "command"

TYPE_MODULE, TYPE_HRL, TYPE_UNKNOWN = range(3)

TASK_COMPILE, TASK_COMPILE_FLY, TASK_GEN_FILE_CACHE, TASK_GEN_ERLANG_CACHE = range(4)